# Gin-Vue-Admin Global Configuration

# jwt configuration
jwt:
  signing-key: 'qmPlus'

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GIN-VUE-ADMIN]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# email configuration
email:
  to: 'xueyin@p1.com'
  port: 25
  from: 'antispam.common@p1.com'
  host: 'smtp.p1.com'
  is-ssl: false
  secret: 'IRy1pbAShK0tFsRH'
  nickname: 'xueyin'

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: 'postgresql'
  oss-type: 'local'
  config-env: 'GVA_CONFIG'
  need-init-data: false
  use-multipoint: false

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80

# Postgresql connect configuration
postgresql:
  host: '10.180.8.52'
  port: '5432'
  config: 'sslmode=disable TimeZone=Asia/Shanghai client_encoding=UTF8'
  db-name: 'putong-moderationlog'
  username: 'putong'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 10
  prefer-simple-protocol: true
  logger: false

# local configuration
local:
  path: 'uploads/file'

# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 和 域名地址)
qiniu:
  zone: 'ZoneHuadong'
  bucket: 'qm-plus-img'
  img-path: 'http://qmplusimg.henrongyi.top'
  use-https: false
  access-key: '25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ'
  secret-key: 'pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY'
  use-cdn-domains: false